from django.urls import path
from .views import (
    RegisterAPIView,
    LoginAPIView,
    ProfileDetailsAPIView,
    ProfileUpdateAPIView,
    ProfileUpdateFieldAPIView,
    AssignmentListAPIView,
    AssignmentCreateAPIView,
    AssignmentDetailAPIView,
    AssignmentUpdateAPIView,
    AssignmentDeleteAPIView,
    AssignmentSubmissionAPIView,
    AssignmentGradeAPIView,
    BookListAPIView,
    BookCreateAPIView,
    BookDetailAPIView,
    BookDeleteAPIView,
    MyGradesAPIView,
    TeacherGradesAPIView,
    GradeSetAPIView,
    AllGradesAPIView,
    CalendarEventListAPIView,
    CalendarEventCreateAPIView,
    CalendarEventDetailAPIView,
    CalendarEventDeleteAPIView,
)

urlpatterns = [
    path('register', RegisterAPIView.as_view(), name='register'),
    path('login', LoginAPIView.as_view(), name='login'),
    path('user/profile', ProfileDetailsAPIView.as_view(), name='profile-get'),
    path('user/profile/update', ProfileUpdateAPIView.as_view(), name='profile-update'),
    path('user/profile/update/v2', ProfileUpdateFieldAPIView.as_view(), name='profile-update-field'),
    path('assignments/', AssignmentListAPIView.as_view(), name='assignments-list'),
    path('assignments/create/', AssignmentCreateAPIView.as_view(), name='assignments-create'),
    path('assignments/<int:pk>/', AssignmentDetailAPIView.as_view(), name='assignments-detail'),
    path('assignments/<int:pk>/update/', AssignmentUpdateAPIView.as_view(), name='assignments-update'),
    path('assignments/<int:pk>/delete/', AssignmentDeleteAPIView.as_view(), name='assignments-delete'),
    path('assignments/<int:assignment_id>/submit/', AssignmentSubmissionAPIView.as_view(), name='assignments-submit'),
    path('submissions/<int:submission_id>/grade/', AssignmentGradeAPIView.as_view(), name='assignments-grade'),
    path('books/', BookListAPIView.as_view(), name='books-list'),
    path('books/create/', BookCreateAPIView.as_view(), name='books-create'),
    path('books/<int:pk>/', BookDetailAPIView.as_view(), name='books-detail'),
    path('books/<int:pk>/delete/', BookDeleteAPIView.as_view(), name='books-delete'),
    path('grades/my/', MyGradesAPIView.as_view(), name='my-grades'),
    path('grades/teacher/', TeacherGradesAPIView.as_view(), name='teacher-grades'),
    path('grades/all/', AllGradesAPIView.as_view(), name='all-grades'),
    path('grades/<int:submission_id>/set/', GradeSetAPIView.as_view(), name='set-grade'),
    path('calendar/', CalendarEventListAPIView.as_view(), name='calendar-list'),
    path('calendar/create/', CalendarEventCreateAPIView.as_view(), name='calendar-create'),
    path('calendar/<int:pk>/', CalendarEventDetailAPIView.as_view(), name='calendar-detail'),
    path('calendar/<int:pk>/delete/', CalendarEventDeleteAPIView.as_view(), name='calendar-delete'),

]
